#!/usr/bin/env bash

## python3
sudo apt update
sudo apt install -y python3 python3-pip python3-venv

## virtual env
# $ python3 -m venv .venv
# $ source .venv/bin/activate
# $ pip install ...
# ...
# $ deactivate

## install uv
curl -LsSf https://astral.sh/uv/install.sh | sh
