#!/usr/bin/env bash

DOTFILES_DIR=$(dirname "$(readlink "$0" || echo "$0")")

DELETE=0
INSTALL=1
STOW_FOLDERS=()

function set_stow_folders() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -D | --delete)
                DELETE=1
                INSTALL=0
                shift
                ;;
            -U | --update)
                DELETE=1
                INSTALL=1
                shift
                ;;
            -h | --help)
                usage
                exit 1
                ;;
            -p | --private)
                set_default
                private
                shift
                ;;
            -s | --shared)
                set_default
                shared
                shift
                ;;
            *)
                STOW_FOLDERS+=("$1")
                shift
                ;;
        esac
    done

    if [[ ${#STOW_FOLDERS[@]} -eq 0 ]]; then
        set_all
    fi
}

function reset() {
    STOW_FOLDERS=()
}

function set_default() {
    STOW_FOLDERS=(ghostty tmux vim ripgrep git tig lazygit zsh nvim)
}

function set_all() {
    mapfile -t STOW_FOLDERS < <(/bin/ls -d -- */ | sed 's/\///g')
}

function shared() {
    STOW_FOLDERS+=()
    case ${OSTYPE} in
        darwin*)
            STOW_FOLDERS+=(ghostty-mac iterm2)
            ;;
        linux-gnu*)
            STOW_FOLDERS+=(ghostty-linux)
            ;;
        *)
            reset
            ;;
    esac
}

function private() {
    STOW_FOLDERS+=(wakatime)
    case ${OSTYPE} in
        darwin*)
            STOW_FOLDERS+=(ghostty-mac iterm2)
            ;;
        linux-gnu*)
            STOW_FOLDERS+=(ghostty-linux xmonad rofi nitrogen)
            ;;
        *)
            reset
            ;;
    esac
}

function usage() {
    cat << EOF
usage: $(basename "${0}") [--help] [--list] [--update | --delete]
                        [--private | --shared] [dirs]

options:
    --help,    -h     print this
    --delete,  -D     delete dotfiles
    --private, -p     select dotfiles for a private host
    --shared,  -s     select dotfiles for a shared host

EOF
}

function restore_file() {
    if [[ $# -lt 1 ]]; then
        echo "Pass at least one dotfile name: $1 ($#)"
        exit 1
    fi

    FILENAME="$1"

    if [[ -f ${HOME}/${FILENAME}.backup ]]; then
        if [[ -L ${HOME}/${FILENAME} ]]; then
            /bin/rm -f "${HOME}/${FILENAME}"
        fi
        /bin/mv -f "${HOME}/${FILENAME}.backup" "${HOME}/${FILENAME}"
    fi
}

function backup_file() {
    if [[ $# -lt 1 ]]; then
        echo "Pass at least one dotfile name"
        exit 1
    fi

    FILENAME="$1"

    if [[ -e ${HOME}/${FILENAME} ]]; then
        if [[ ! -L ${HOME}/${FILENAME} ]]; then
            /bin/mv -f "${HOME}/${FILENAME}" "${HOME}/${FILENAME}.backup"
        fi
    fi
}

function restore_all() {
    restore_file ".bashrc"
    restore_file ".profile"
    restore_file ".bash_aliases"
    restore_file ".zshrc"
    restore_file ".zshenv"
}

function backup_all() {
    backup_file ".bashrc"
    backup_file ".profile"
    backup_file ".bash_aliases"
    backup_file ".zshrc"
    backup_file ".zshenv"
}

function credential() {
    printf "Deleting   %-17s ...   " "password? (y/N)"
    read -r input
    if [[ -z $input ]]; then
        credential
    elif [[ $input == 'n' ]] || [[ $input == 'N' ]]; then
        :
    elif [[ $input == 'y' ]] || [[ $input == 'Y' ]]; then
        rm -f "$HOME/.git-credentials"
    else
        credential
    fi
}

function update() {
    if [[ ${DELETE} -eq 1 ]]; then
        for folder in "${STOW_FOLDERS[@]}"; do
            restore_all
            printf "Deleting   %-17s" "$folder"
            stow -t "$HOME" -D "$folder" 2> /dev/null
            echo " ...   Done"
        done
        credential
    fi

    if [[ ${INSTALL} -eq 1 ]]; then
        for folder in "${STOW_FOLDERS[@]}"; do
            backup_all
            printf "Installing %-17s" "$folder"
            stow --ignore='\.DS_Store' -t "$HOME" -S "$folder"
            echo " ...   Done"
        done
    fi
}

function main() {
    pushd "$DOTFILES_DIR" > /dev/null || exit
    set_stow_folders "$@"
    update
    popd > /dev/null || exit
}

main "$@"
