require('plugin.snacks')
require('plugin.catppuccin')
require('plugin.treesitter')
require('plugin.undotree')
require('plugin.lsp')
require('plugin.conform')
require('plugin.lint')
require('plugin.blink')
require('plugin.copilot')

pcall(require, 'plugin.wakatime')
