require('plugin.snacks')
require('plugin.oil')
require('plugin.catppuccin')
require('plugin.treesitter')
require('plugin.undotree')
require('plugin.gitsigns')
require('plugin.fugitive')
require('plugin.lsp')
require('plugin.conform')
require('plugin.lint')
require('plugin.blink')
require('plugin.copilot')
require('plugin.comment')
require('plugin.markdown-preview')
require('plugin.vim-table-mode')
require('plugin.markdown-toc')
require('plugin.skkeleton')

pcall(require, 'plugin.wakatime')
