require("plugin.skkeleton")
require("plugin.gitsigns")
require("plugin.zdiff")
require("plugin.surround")
require("plugin.markdown")
require("plugin.oil")
require("plugin.snacks")
require("plugin.chainsaw")
require("plugin.tabout")
require("plugin.autoclose")
require("plugin.colorizer")
pcall(require, "plugin.wakatime")
