#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 1
bspc config window_gap 8

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 10
bspc config right_padding 10

bspc config split_ratio 0.58
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a firefox desktop='^2'
