require('plugin.snacks')
require('plugin.oil')
require('plugin.treesitter')
require('plugin.undotree')
require('plugin.gitsigns')
require('plugin.fugitive')
require('plugin.jujutsu')
require('plugin.lsp')
require('plugin.conform')
require('plugin.lint')
require('plugin.blink')
require('plugin.surround')
require('plugin.comment')
require('plugin.markdown')
require('plugin.skkeleton')

pcall(require, 'plugin.wakatime')
