# Some basic mocha colors.
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_peach "#fab387"
set -g @ctp_green "#a6e3a1"
set -g @ctp_blue "#89b4fa"
set -g @ctp_text "#cdd6f4"
set -g @ctp_surface0 "#313244"
set -g @ctp_base "#1e1e2e"

set -gF mode-style "fg=#{@ctp_blue},bg=#{@ctp_base}"

set -gF message-style "fg=#{@ctp_peach},bg=#{@ctp_base}"
set -gF message-command-style "fg=#{@ctp_peach},bg=#{@ctp_base}"

set -g pane-border-style "fg=#{@ctp_blue}"
set -g pane-active-border-style "fg=#{@ctp_blue}"

set -g status "on"
set -g status-justify "left"

set -gF status-style "bg=#{@ctp_base},fg=#{@ctp_text}"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "\
#[fg=#{@ctp_base},bg=#{@ctp_blue},bold] #S \
#[fg=#{@ctp_blue},bg=#{@ctp_base},nobold,nounderscore,noitalics]"
set -g status-right "\
#{prefix_highlight}\
#[fg=#{@ctp_text},bg=#{@ctp_base}] %Y-%m-%d \
#[fg=#{@ctp_surface0},bg=#{@ctp_base},nobold,nounderscore,noitalics]\
#[fg=#{@ctp_text},bg=#{@ctp_surface0}] %I:%M %p \
#[fg=#{@ctp_blue},bg=#{@ctp_surface0},nobold,nounderscore,noitalics]\
#[fg=#{@ctp_base},bg=#{@ctp_blue},bold] #h "

setw -g window-status-activity-style "underscore,fg=#{@ctp_blue},bg=#{@ctp_base}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#{@ctp_blue},bg=#{@ctp_base}"
setw -g window-status-format "\
#[fg=#{@ctp_text},bg=#{@ctp_base}] #I #W "
setw -g window-status-current-format "\
#[fg=#{@ctp_mauve},bg=#{@ctp_base},bold] #I #W "

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "\
#[fg=#{@ctp_green}]#[bg=#{@ctp_base}]#[fg=#{@ctp_base}]#[bg=#{@ctp_green}] "
set -g @prefix_highlight_output_suffix " "

# vim: set ft=tmux :
