require('plugins.cmp')
require('plugins.conform')
require('plugins.lspconfig')
require('plugins.lint')

require('plugins.operation')
require('plugins.edit')
-- require('plugins.claude')
require('plugins.color')
pcall(require, 'plugins.wakatime')
