require("plugin.skkeleton")
require("plugin.gitsigns")
require("plugin.zdiff")
require("plugin.surround")
require("plugin.markdown")
require("plugin.oil")
require("plugin.snacks")
pcall(require, "plugin.wakatime")
