vim.keymap.set('n', 'Y', 'y$', { silent = true })
vim.keymap.set('n', '[q', '<cmd>cprevious<cr>', { silent = true })
vim.keymap.set('n', ']q', '<cmd>cnext<cr>', { silent = true })
vim.keymap.set('n', '<C-h>', '<cmd>bprev<cr>', { silent = true })
vim.keymap.set('n', '<C-l>', '<cmd>bnext<cr>', { silent = true })
vim.keymap.set('n', '<leader>d', vim.diagnostic.open_float, { noremap = true, silent = true })
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { noremap = true, silent = true })
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { noremap = true, silent = true })
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { noremap = true, silent = true })
