vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.signcolumn = "yes:2"
vim.opt.colorcolumn = "+1"
vim.opt.textwidth = 120
vim.o.undofile = true
vim.o.autoread = true
vim.o.laststatus = 3
vim.o.cmdheight = 1
vim.o.clipboard = "unnamedplus" -- See :checkhealth provider
